name: New Integration Request
description: Need an Integration that isn't in our catalog yet? Ask here!
title: "feat: Add integration with: #SOFTWARE_NAME"
labels: ["backend", "embedded-catalog", "good first issue", "🔌 Connector"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this! 
        Please fill one ticket per platform you want to integrate with.
  - type: dropdown
    id: software_category
    attributes:
      label: "What type of software do you want to build integrations with?"
      multiple: true
      options:
        - Accounting
        - Calendar
        - Cybersecurity
        - CRM
        - Data Warehouse
        - Document Signature
        - Ecommerce
        - Email
        - File Storage
        - HRIS
        - Logging
        - Marketing Automation
        - Payments
        - Point of Sale
        - Source Code Management
        - Telematics and IOT
        - Ticketing
        - Other
    validations:
      required: true
  - type: textarea
    id: platforms
    attributes:
      label:  "Which specific platforms would you integrate with?"
      description: " (example: Salesforce, Hubspot, Zendesk, Jira...)"
  - type: textarea
    id: objects
    attributes:
      label: "Which specific objects would you integrate with?"
      description: "(example: Deals and Contacts from CRMs)"
  - type: dropdown
    id: readwrite
    attributes:
      label: Do you anticipate to mostly read, or write data?
      multiple: true
      options:
        - Read mostly
        - Write mostly
        - Read and write
    validations:
      required: true
  - type: textarea
    id: notes
    attributes:
      label: "Please share any detail you want here"    