workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    merge-code-samples-into-spec:
        inputs:
            - location: registry.speakeasyapi.dev/panora/panora/panora-open-api-swagger
        overlays:
            - location: registry.speakeasyapi.dev/panora/panora/code-samples-typescript-my-first-target:main
            - location: registry.speakeasyapi.dev/panora/panora/code-samples-python:main
            - location: registry.speakeasyapi.dev/panora/panora/go-sdk:main
            - location: registry.speakeasyapi.dev/panora/panora/code-samples-ruby:main
        output: packages/api/swagger/openapi-with-code-samples.yaml
        registry:
            location: registry.speakeasyapi.dev/panora/panora/merge-code-samples-into-spec
targets: {}
