name: Export Docker Images (Frontend Magic Links Selfhosted)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: SELF_HOSTED

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Frontend (Magic Links)
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          file: ./apps/magic-link/Dockerfile
          push: true
          tags: panoradotdev/frontend-magic-links:selfhosted
          build-args: |
            VITE_BACKEND_DOMAIN=${{ secrets.VITE_BACKEND_DOMAIN }}