name: docker-compose.yml - Healthcheck

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  docker:
    name: Run containers
    runs-on: ubuntu-latest
    environment: SELF_HOSTED
    env:
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      BACKEND_PORT: ${{ secrets.BACKEND_PORT }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      DISTRIBUTION: ${{ secrets.DISTRIBUTION }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      REDIS_HOST: ${{ secrets.REDIS_HOST }}
      REDIS_PORT: ${{ secrets.REDIS_PORT }}
      REDIS_PASS: ${{ secrets.REDIS_PASS }}
      NEXT_PUBLIC_BACKEND_DOMAIN: ${{ secrets.NEXT_PUBLIC_BACKEND_DOMAIN }}
      NEXT_PUBLIC_MAGIC_LINK_DOMAIN: ${{ secrets.NEXT_PUBLIC_MAGIC_LINK_DOMAIN }}
    steps:
      - uses: actions/checkout@v3
      - uses: isbang/compose-action@v1.5.1
